# =========================
# Global settings
# =========================
#use_sim_time: true

# =========================
# Planner Server (NavFn)
# =========================
planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0

# =========================
# Controller Server (DWB)
# =========================
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0

    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      # ---- Velocity limits (Leo-friendly, conservative) ----
      min_vel_x: -0.4
      max_vel_x: 0.6
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 1.5

      # ---- Acceleration limits ----
      acc_lim_x: 1.0
      acc_lim_theta: 2.5

      # ---- Sampling ----
      vx_samples: 10
      vtheta_samples: 20
      sim_time: 1.7

      # ---- Goal tolerances ----
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      trans_stopped_velocity: 0.05

      # ---- CRITICAL PART (your crash fix) ----
      critics:
        - RotateToGoal
        - Oscillation
        - BaseObstacle
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist

      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0


# =========================
# Local Costmap (with depth camera)
# =========================
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 10.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 6
      height: 6
      resolution: 0.05

      plugins:
        - obstacle_layer
        - inflation_layer

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: depth_camera
        depth_camera:
          topic: /depth_camera/points
          sensor_frame: camera_link
          observation_persistence: 0.0
          expected_update_rate: 10.0
          data_type: "PointCloud2"
          min_obstacle_height: 0.1
          max_obstacle_height: 2.0
          obstacle_max_range: 5.0
          obstacle_min_range: 0.2
          clearing: true
          marking: true
          raytrace_max_range: 5.0
          raytrace_min_range: 0.2

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55
        cost_scaling_factor: 2.0


# =========================
# Global Costmap
# =========================
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_footprint
      resolution: 0.05
      track_unknown_space: false

      plugins:
        - static_layer
        - inflation_layer

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55


# =========================
# BT Navigator
# =========================
bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: >
      /opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml


# =========================
# Behavior Server (recoveries)
# =========================
behavior_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: odom
    robot_base_frame: base_footprint
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2


# =========================
# Lifecycle
# =========================
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - planner_server
      - controller_server
      - behavior_server
      - bt_navigator
