# =========================
# Global settings
# =========================
#use_sim_time: true

# =========================
# Planner Server (NavFn)
# =========================
planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0

    #planner_plugins: ["GridBased"]
    #GridBased:
    #  plugin: "nav2_navfn_planner/NavfnPlanner"
    #  tolerance: 0.5
    #  use_astar: false
    #  allow_unknown: true


# =========================
# Controller Server (DWB)
# =========================
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0

    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      # ---- Velocity limits (Leo-friendly, conservative) ----
      min_vel_x: -0.4
      max_vel_x: 0.6
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 1.5

      # ---- Acceleration limits ----
      acc_lim_x: 1.0
      acc_lim_theta: 2.5

      # ---- Sampling ----
      vx_samples: 10
      vtheta_samples: 20
      sim_time: 1.7

      # ---- Goal tolerances ----
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      trans_stopped_velocity: 0.05

      # ---- CRITICAL PART (your crash fix) ----
      critics:
        - RotateToGoal
        - Oscillation
        - BaseObstacle
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist

      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0


# =========================
# Local Costmap (no depth yet)
# =========================
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 10.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 6
      height: 6
      resolution: 0.05

      plugins:
        - obstacle_layer
        - inflation_layer

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55


# =========================
# Global Costmap
# =========================
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_footprint
      resolution: 0.05
      track_unknown_space: false

      plugins:
        - static_layer
        - inflation_layer

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55


# =========================
# BT Navigator
# =========================
bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: >
      /opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml


# =========================
# Lifecycle
# =========================
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - planner_server
      - controller_server
      - bt_navigator
